name: 'Sylver check'
description: 'Run `sylver check` on your source code and upload the analysis results to your dashboard.'
icon: 'sylver-logo.png'
inputs:
  token:
    description: 'Sylver token for the current repository'
    required: true  
