name: 'Sylver check'
description: 'Run `sylver check` on your source code and upload the analysis results to your dashboard.'
branding:
  color: blue
  icon: check-square
inputs:
  token:
    description: 'Sylver token for the current repository'
    required: true  
